Repository Azure/data-api-builder, pull requests merged in 2024-04, with the labels that each got.

#2051 Removing wrong FK definition
  src/Core/Services/MetadataProviders/SqlMetadataProvider.cs
  src/Service.Tests/Unittests/SqlMetadataProviderUnitTests.cs
Labels: bug, mssql pgsql mysql

#2170 using linux image for building docker image
  onebranch/Dockerfile
Labels: bug

#2056 Multiple-create: Order determination for insertions
  config-generators/mssql-commands.txt
  config-generators/mysql-commands.txt
  config-generators/postgresql-commands.txt
  src/Config/DatabasePrimitives/DatabaseObject.cs
  src/Core/Models/RelationshipFields.cs
  src/Core/Resolvers/MultipleCreateOrderHelper.cs
  src/Service.Tests/DatabaseSchema-MsSql.sql
  src/Service.Tests/DatabaseSchema-MySql.sql
  src/Service.Tests/DatabaseSchema-PostgreSql.sql
  src/Service.Tests/Snapshots/ConfigurationTests.TestReadingRuntimeConfigForMsSql.verified.txt
  src/Service.Tests/Snapshots/ConfigurationTests.TestReadingRuntimeConfigForMySql.verified.txt
  src/Service.Tests/Snapshots/ConfigurationTests.TestReadingRuntimeConfigForPostgreSql.verified.txt
  src/Service.Tests/Unittests/MultipleCreateUnitTests/MsSqlMultipleCreateOrderHelperUnitTests.cs
  src/Service.Tests/Unittests/MultipleCreateUnitTests/MultipleCreateOrderHelperUnitTests.cs
  src/Service.Tests/Unittests/MultipleCreateUnitTests/MySqlMultipleCreateOrderHelperUnitTests.cs
  src/Service.Tests/Unittests/MultipleCreateUnitTests/PgSqlMultipleCreateOrderHelperUnitTests.cs
  src/Service.Tests/dab-config.MsSql.json
  src/Service.Tests/dab-config.MySql.json
  src/Service.Tests/dab-config.PostgreSql.json
Labels: Multiple mutations

#2149 add devcontainer.json config for .net 6 -Codespaces
  .devcontainer/devcontainer.json
Labels: enhancement, usability

#2187 [Cherrypick] Delete redundant directory
  onebranch/Dockerfile
Labels: 🍒Cherrypick

#1994 Multiple Create - Database Query Generation and Selection Set Resolution
  config-generators/mssql-commands.txt
  src/Config/DataApiBuilderException.cs
  src/Core/Resolvers/BaseSqlQueryBuilder.cs
  src/Core/Resolvers/IQueryBuilder.cs
  src/Core/Resolvers/IQueryEngine.cs
  src/Core/Resolvers/IQueryExecutor.cs
  src/Core/Resolvers/MsSqlQueryBuilder.cs
  src/Core/Resolvers/MsSqlQueryExecutor.cs
  src/Core/Resolvers/QueryExecutor.cs
  src/Core/Resolvers/Sql Query Structures/BaseSqlQueryStructure.cs
  src/Core/Resolvers/Sql Query Structures/MultipleCreateStructure.cs
  src/Core/Resolvers/Sql Query Structures/SqlInsertQueryStructure.cs
  src/Core/Resolvers/Sql Query Structures/SqlQueryStructure.cs
  src/Core/Resolvers/SqlMutationEngine.cs
  src/Core/Resolvers/SqlQueryEngine.cs
  src/Core/Services/MetadataProviders/ISqlMetadataProvider.cs
  src/Core/Services/MetadataProviders/SqlMetadataProvider.cs
  src/Core/Services/MultipleMutationInputValidator.cs
  src/Service.GraphQLBuilder/GraphQLUtils.cs
  src/Service.GraphQLBuilder/Mutations/CreateMutationBuilder.cs
  src/Service.Tests/Authorization/GraphQL/CreateMutationAuthorizationTests.cs
  src/Service.Tests/DatabaseSchema-MsSql.sql
  src/Service.Tests/Snapshots/ConfigurationTests.TestReadingRuntimeConfigForMsSql.verified.txt
  src/Service.Tests/SqlTests/GraphQLMutationTests/MsSqlGraphQLMutationTests.cs
  src/Service.Tests/SqlTests/GraphQLMutationTests/MultipleCreateMutationTests/MsSqlMultipleCreateMutationTests.cs
  src/Service.Tests/SqlTests/GraphQLMutationTests/MultipleCreateMutationTests/MultipleCreateMutationTestBase.cs
  src/Service.Tests/SqlTests/RestApiTests/Insert/MsSqlInsertApiTests.cs
  src/Service.Tests/SqlTests/RestApiTests/Patch/MsSqlPatchApiTests.cs
  src/Service.Tests/SqlTests/RestApiTests/Put/MsSqlPutApiTests.cs
  src/Service.Tests/dab-config.MsSql.json
Labels: Multiple mutations
